version: "3.8"

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data

  webhook:
    build: .
    container_name: webhook
    ports:
      - "3003:3003"
    environment:
      REDIS_URL: redis://default:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - redis

volumes:
  redis-data:
